source ~/.libraries/vimrc/vimrcs/basic.vim
source ~/.libraries/vimrc/vimrcs/filetypes.vim
source ~/.libraries/vimrc/vimrcs/extended.vim

" https://github.com/junegunn/vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin( '~/.vim/plugged' )
    Plug 'https://github.com/junegunn/vim-easy-align.git'
    Plug 'https://github.com/ervandew/supertab.git'
    Plug 'https://github.com/mhinz/vim-startify'
    Plug 'https://github.com/wellle/targets.vim'
    Plug 'https://github.com/scrooloose/nerdcommenter'
    Plug 'https://github.com/vim-airline/vim-airline'
    Plug 'https://github.com/scrooloose/syntastic.git'
    Plug 'https://github.com/StanAngeloff/php.vim.git'
    "Plug 'https://github.com/vim-vdebug/vdebug'
call plug#end()

set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set smartindent
set number
set autowriteall
set diffopt+=iwhite
set diffopt+=icase
set diffopt+=filler

autocmd BufWritePre,BufRead * :%s/\s\+$//e | retab

syntax on
filetype on
let php_html_in_strings=1
let php_html_in_heredoc=1

set <Home>=[29~
set <End>=[31~
set foldmethod=indent
set textwidth=80
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
highlight extraWhiteSpace ctermbg=darkgreen guibg=darkgreen
if &diff
    colorscheme industry
    highlight! link DiffText Todo
    syntax off
endif
match OverLength /\%81v.\+/
" https://github.com/scrooloose/syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_aggregate_errors = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_html_tidy_exec = 'tidy5'
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_php_checkers = ['php', 'phpcbf', 'phpcs']
let g:syntastic_sql_checkers = ['sqlint']
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
