#!/usr/bin/env php
<?php
$cssFile = "assets/index.css";
$cssLint = '';
if (false === empty(shell_exec('which csslint'))) {
    $cssLint = "&& csslint $cssFile";
}

$output  = shell_exec(
    "rm assets/index.css && \
        sass assets/index.scss $cssFile $cssLint"
);
echo "$output \n \n";
# grunt
# mysqldump
