#!/usr/bin/env php
<?php
// An example hook script to verify what is about to be pushed.  Called by "git
// push" after it has checked the remote status, but before anything has been
// pushed.  If this script exits with a non-zero status nothing will be pushed.
//
// This hook is called with the following parameters:
//
// $1 -- Name of the remote to which the push is being done
// $2 -- URL to which the push is being done
//
// If pushing without using a named remote those arguments will be equal.
//
// Information about the commits which are being pushed is supplied as lines to
// the standard input in the form:
//
//   <local ref> <local sha1> <remote ref> <remote sha1>
//
echo "merge checklist

- Did you write the merge branch in a development environment?
- Does your work look good to you?
- Does it pass all of its tests?

- Did you publish this to a beta environment?
- Have the users reviewed, and approved it in beta?
- Has it continued to pass its tests?
- Have you checked the merge commit for unexpected changes to other files?";
$input = readline("Have you walked through these steps? y | n");
if ('y' != substr($input, 0, 1)) {
    exit(0);
}
/*
rm style.css &&
    sass --update -t compressed .
wget --spider -r -nd -H -l 1 -w 2 -o wget.log http://smalls.rocks &
*/
