#!/usr/bin/env php
<?php
$output = shell_exec('\phpunit .');
echo "$output\n";
/*
 * Abort the commit if the unit test fails, or throws any execution errors.
 */
if (false != stripos($output, 'FAILURES')
|| false  != stripos($output, 'ERRORS')
|| false  != stripos($output, 'Fatal')
) {
    exit(1);
}

$cssFile   = "assets/index.css";
$cssLint   = '';
$cssDelete = '';
if (true === file_exists($cssFile)) {
    $cssDelete = "rm $cssFile &&";
}
shell_exec("$cssDelete sass assets/index.scss $cssFile");
/*
 * Sass echoes its output rather than returning it, so instead we evaluate
 * whether the CSS file has been recreated, or if deletion was the only
 * successful action.
 */
if (false === file_exists($cssFile)) {
    exit(1);
}
