#!/usr/bin/env php
<?php
// A prepush hook will create an infinite loop if we run another push within it.
// A lock file feels like the most appropriate solution since I still want to
// update Github the same way I do here.
//
// We can also use this time to check Github for content for other developers,
// and exit if we have not properly merged it.
$lockFile = __DIR__ . '/pre-push.lock';
if (false === file_exists($lockFile)) {
    touch($lockFile);
    $output = "\n\n" . shell_exec('git push github') . "\n\n";
    // TODO What kind of output would abort a push?
    echo $output;
    return;
}
shell_exec("rm $lockFile");
